### ISSUE TITLE
error:0909006C:PEM routines:get_name:no start line

### ISSUE THREAD

**Issue by mkumarjha** [Mahanteshkumbar/Angular-8-Laravel-6-user-Login#3]
I was trying to run this app in my local system getting this issue, Plz let me know how i can resolve it  ?

{
    "message": "It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line",
    "exception": "InvalidArgumentException",
    "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/lcobucci/jwt/src/Signer/OpenSSL.php",
    "line": 90,
    "trace": [
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/lcobucci/jwt/src/Signer/OpenSSL.php",
            "line": 47,
            "function": "validateKey",
            "class": "Lcobucci\\JWT\\Signer\\OpenSSL",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/lcobucci/jwt/src/Signer/OpenSSL.php",
            "line": 21,
            "function": "getPrivateKey",
            "class": "Lcobucci\\JWT\\Signer\\OpenSSL",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/lcobucci/jwt/src/Signer/BaseSigner.php",
            "line": 36,
            "function": "createHash",
            "class": "Lcobucci\\JWT\\Signer\\OpenSSL",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/lcobucci/jwt/src/Builder.php",
            "line": 470,
            "function": "sign",
            "class": "Lcobucci\\JWT\\Signer\\BaseSigner",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/lcobucci/jwt/src/Builder.php",
            "line": 450,
            "function": "createSignature",
            "class": "Lcobucci\\JWT\\Builder",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/league/oauth2-server/src/Entities/Traits/AccessTokenTrait.php",
            "line": 41,
            "function": "getToken",
            "class": "Lcobucci\\JWT\\Builder",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php",
            "line": 28,
            "function": "convertToJWT",
            "class": "Laravel\\Passport\\Bridge\\AccessToken",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/league/oauth2-server/src/AuthorizationServer.php",
            "line": 202,
            "function": "generateHttpResponse",
            "class": "League\\OAuth2\\Server\\ResponseTypes\\BearerTokenResponse",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/passport/src/PersonalAccessTokenFactory.php",
            "line": 114,
            "function": "respondToAccessTokenRequest",
            "class": "League\\OAuth2\\Server\\AuthorizationServer",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/passport/src/PersonalAccessTokenFactory.php",
            "line": 71,
            "function": "dispatchRequestToAuthorizationServer",
            "class": "Laravel\\Passport\\PersonalAccessTokenFactory",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/passport/src/HasApiTokens.php",
            "line": 67,
            "function": "make",
            "class": "Laravel\\Passport\\PersonalAccessTokenFactory",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/app/Http/Controllers/Auth/PassportController.php",
            "line": 40,
            "function": "createToken",
            "class": "App\\User",
            "type": "->"
        },
        {
            "function": "register",
            "class": "App\\Http\\Controllers\\Auth\\PassportController",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
            "line": 54,
            "function": "call_user_func_array"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
            "line": 45,
            "function": "callAction",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 219,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 176,
            "function": "runController",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 681,
            "function": "run",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 130,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/app/Http/Middleware/CORS.php",
            "line": 18,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "App\\Http\\Middleware\\CORS",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php",
            "line": 41,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php",
            "line": 59,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\ThrottleRequests",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 105,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 683,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 658,
            "function": "runRouteWithinStack",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 624,
            "function": "runRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 613,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 170,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 130,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/app/Http/Middleware/CORS.php",
            "line": 18,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "App\\Http\\Middleware\\CORS",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
            "line": 27,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
            "line": 63,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/fideloper/proxy/src/TrustProxies.php",
            "line": 57,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Fideloper\\Proxy\\TrustProxies",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 105,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 145,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 110,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/public/index.php",
            "line": 55,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/media/mithilesh/Extras/RND/Angular-8-Laravel-6-user-Login/laravelAngularApi/server.php",
            "line": 21,
            "function": "require_once"
        }
    ]
}

**Comment by mattnelsonuk** [comment]
Delete any oauth stuff you have in your databse (tokens, clients etc) then run 
```
php artisan passport:keys --force
php artisan passport:install
```

Make sure you get two keys created in your storage folder. You can create these manually if you need to.

**Comment by Mahanteshkumbar** [comment]
Passport Installation and Configuration
For more information read  [Laravel Passport](https://laravel.com/docs/6.x/passport)
