### ISSUE TITLE
API's not working

### ISSUE THREAD

**Issue by officialahk** [Mahanteshkumbar/Angular-8-Laravel-6-user-Login#6]
Laravel api project is not working.
![Capture](https://user-images.githubusercontent.com/41996537/75362620-d81b3d00-58da-11ea-8aae-27aa0cb15e1a.PNG)

**Comment by meTech1021** [comment]
Excuse me sir.
I followed your course, although token is not created.
Please help me.
Thanks.

**Comment by artvation** [comment]
Unfortunately I have exactly the same issue.
Any help or tips?

**Comment by artvation** [comment]
@officialahk could you solve this meanwhile?

**Comment by Mahanteshkumbar** [comment]
> Excuse me sir.
> I followed your course, although token is not created.
> Please help me.
> Thanks.

Can you please provide more details or any specific error message

**Comment by Mahanteshkumbar** [comment]
Kindly go through latest angular and laravel Sanctum api project

https://github.com/Mahanteshkumbar/Laravel7-Angular10-roles-permission
